apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
    namespace: petclinic
spec:
    ports:
    - name: discovery-server
      targetPort: 8761
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: discovery-server
    type: {{ .Values.service.type }}