apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
    namespace: petclinic
spec:
    ports:
    - name: vets-service
      targetPort: 8083
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: vets-service
    type: {{ .Values.service.type }}