apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
    namespace: petclinic
spec:
    ports:
    - name: grafana-server
      targetPort: 3000
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: grafana-server
    type: {{ .Values.service.type }}