apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: petclinic
  labels:
    app: admin-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}"
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: 512M
      initContainers:
      - name: init-config-server
        image: busybox
        command: ['sh', '-c', 'until nc -z config-server-svc 8888; do echo waiting for config-server; sleep 2; done;']
      - name: init-discovery-server
        image: busybox
        command: ['sh', '-c', 'until nc -z discovery-server-svc 8761; do echo waiting for discovery-server; sleep 2; done;']