apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
    namespace: petclinic
spec:
    ports:
    - name: admin-server
      targetPort: 9090
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: admin-server
    type: {{ .Values.service.type }}